#import <Foundation/Foundation.h>
#import "SWGAppProjectReaderServiceModel.h"
#import "SWGAppProjectWriterServiceModel.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGAppProjectApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGAppProjectApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGAppProjectApi*) sharedAPI;
///
///
/// 
/// Post app project
///
/// @param appProjectWriterServiceModel Definition of the appProject
/// 
///
/// @return SWGAppProjectReaderServiceModel*
-(NSNumber*) postWithCompletionBlock :(SWGAppProjectWriterServiceModel*) appProjectWriterServiceModel 
    
    completionHandler: (void (^)(SWGAppProjectReaderServiceModel* output, NSError* error))completionBlock;
    


///
///
/// 
/// Get
///
/// @param _id ID
/// 
///
/// @return SWGAppProjectReaderServiceModel*
-(NSNumber*) getWithCompletionBlock :(NSNumber*) _id 
    
    completionHandler: (void (^)(SWGAppProjectReaderServiceModel* output, NSError* error))completionBlock;
    



@end
