#import <Foundation/Foundation.h>
#import "SWGAppReaderServiceModel.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGAppApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGAppApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGAppApi*) sharedAPI;
///
///
/// 
/// Get all apps
///
/// 
///
/// @return NSArray<SWGAppReaderServiceModel>*
-(NSNumber*) getAllWithCompletionBlock :
    (void (^)(NSArray<SWGAppReaderServiceModel>* output, NSError* error))completionBlock;
    


///
///
/// 
/// Get App Id
///
/// @param _id id
/// 
///
/// @return SWGAppReaderServiceModel*
-(NSNumber*) getWithCompletionBlock :(NSNumber*) _id 
    
    completionHandler: (void (^)(SWGAppReaderServiceModel* output, NSError* error))completionBlock;
    



@end
