#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGAppProjectWriterServiceModel
@end

@interface SWGAppProjectWriterServiceModel : SWGObject


@property(nonatomic) NSNumber* idApp;

@property(nonatomic) NSNumber* idQuality;

@property(nonatomic) NSString* instruction;

@property(nonatomic) NSArray* /* NSString */ questionOptions;

@property(nonatomic) NSString* title;

@property(nonatomic) NSString* urlNotification;

@end
