#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGAppProjectReaderServiceModel
@end

@interface SWGAppProjectReaderServiceModel : SWGObject


@property(nonatomic) NSString* appName;

@property(nonatomic) NSString* appProjectState;

@property(nonatomic) NSDate* creationDate;

@property(nonatomic) NSNumber* credit;

@property(nonatomic) NSNumber* idApp;

@property(nonatomic) NSNumber* idAppProject;

@property(nonatomic) NSNumber* idQuality;

@property(nonatomic) NSString* instruction;

@property(nonatomic) NSNumber* nbTaskClosed;

@property(nonatomic) NSNumber* nbTotalTask;

@property(nonatomic) NSString* qualityName;

@property(nonatomic) NSArray* /* NSString */ questionOptions;

@property(nonatomic) NSString* title;

@property(nonatomic) NSString* urlNotification;

@end
