#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGQualityReaderServiceModel.h"


@protocol SWGAppReaderServiceModel
@end

@interface SWGAppReaderServiceModel : SWGObject


@property(nonatomic) NSString* appName;

@property(nonatomic) NSNumber* hasInstruction;

@property(nonatomic) NSNumber* hasQuestionOptions;

@property(nonatomic) NSNumber* idApp;

@property(nonatomic) NSArray<SWGQualityReaderServiceModel>* qualities;

@property(nonatomic) NSString* titleQuestionOptions;

@end
