#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGQualityReaderServiceModel
@end

@interface SWGQualityReaderServiceModel : SWGObject


@property(nonatomic) NSNumber* credit;

@property(nonatomic) NSNumber* idQuality;

@property(nonatomic) NSString* name;

@end
