#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGOutputs.h"


@protocol SWGTaskReaderServiceModel
@end

@interface SWGTaskReaderServiceModel : SWGObject


@property(nonatomic) NSNumber* idTask;

@property(nonatomic) SWGOutputs* outputs;

@property(nonatomic) NSDate* updateDate;

@end
