#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGTaskLineWriterServiceModel
@end

@interface SWGTaskLineWriterServiceModel : SWGObject


@property(nonatomic) NSNumber* idAppProject;

@property(nonatomic) NSArray* /* NSString */ inputs;

@end
